<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <EmbeddedResource Include="..\..\..\Teksty\**\piesn.md" LogicalName="Teksty/%(RecursiveDir)piesn.md" Link="Teksty\%(RecursiveDir)piesn.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Velopack" Version="$(VelopackVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Uwielbienia.Core\Uwielbienia.Core.csproj" />
    <ProjectReference Include="..\Uwielbienia.Link\Uwielbienia.Link.csproj" />
  </ItemGroup>
</Project>
