<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AvaloniaVersion>12.1.3</AvaloniaVersion>
    <!-- vpk w .github/workflows/release.yml czyta tę wersję — musi się zgadzać z biblioteką -->
    <VelopackVersion>1.2.158</VelopackVersion>
  </PropertyGroup>
</Project>
